name: pop_and_pose
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_spinkit: ^5.2.1
  another_flushbar: ^1.12.30
  # google_fonts: ^6.2.1
  connectivity_plus: ^6.1.0
  http: ^1.2.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  logger: ^2.4.0
  get_it: ^8.0.2
  # network_info_plus: ^6.1.0
  # wifi_iot: ^0.3.19+1
  # image_picker: ^1.1.2
  # google_sign_in: ^6.2.1
  # googleapis_auth: ^1.6.0
  # googleapis: ^13.2.0
  # video_player: ^2.9.2
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  image: ^4.3.0
  shared_preferences: ^2.2.2
  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1
  window_manager: ^0.3.6
  step_progress_indicator: ^1.0.2
  device_info_plus: ^11.3.0
  image_picker: ^1.1.2
  file_picker: ^9.0.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
